fs-1819 Added import script.
communitiesuk/funding-service-design-assessment-store pull request #51
Opened 2022-11-28 17:44 UTC by SentientHousePlant

- Adds the import script.
- Adjusts the current insert to do upserting during conflicts.

2022-11-29 10:14 UTC, gidsg commented
Can we document how this process is invoked?

2022-12-05 10:43 UTC, tferns requested changes
Changes look good but think there's a small error in your script

2022-12-05 10:43 UTC, tferns commented on scripts/import_from_application.py
> +    app_store_response_json = requests.get(applications_url).json
```suggestion
    app_store_response_json = requests.get(applications_url).json()
```

2022-12-05 12:56 UTC, tferns approved these changes
Looks good! Loving the small maintenance changes that are gradually making the code better

2022-12-05 15:31 UTC, tferns requested changes
Sorry to revoke my approval, I've noticed some issues when trying to run this script locally

I'll outline them in comments

2022-12-05 16:13 UTC, tferns requested changes
Forgot to submit these comments, my bad...

2022-12-05 16:18 UTC, merged