FS-2105: Add event to update workflow status on inserts
communitiesuk/funding-service-design-assessment-store pull request #71
Opened 2022-12-21 11:29 UTC by tferns

- Start listening to inserts on `Score/Comment`
- After each insert, update `workflow_status` of relevant `AssessmentRecord` if not done already

2022-12-22 07:37 UTC, srh-sloan requested changes
Looks good but could you add some unit tests for this please?

2022-12-22 09:55 UTC, tferns commented
> Looks good but could you add some unit tests for this please?

Good point.  I've added some tests in https://github.com/communitiesuk/funding-service-design-assessment-store/pull/71/commits/1208a05ad7c9cb39a43efb91cd86460e17ab5682 and re-based onto `origin/main`

2022-12-22 13:11 UTC, Adam-W1 approved these changes
👍

2022-12-23 09:24 UTC, johnoneill46 approved these changes

2022-12-23 09:25 UTC, merged